apiVersion: v1
kind: Pod
metadata:
   name: webapp
   labels:
     env: test
     app: webapp   
spec:
  containers:
    - name: webapp_container
      image: sureshgattupalli/webapp:tagVersion
      ports: 
       - containerPort: 8088
