apiVersion: v1
kind: Service
metadata:
  name: webapp-srv
  labels:
    app: webapp
spec:
  type: NodePort
  ports:
   -  nodePort: 31001
      port: 80
      targetPort: 8088
  selector:
    app: webapp
